### ISSUE TITLE
Opening sentence reads repetitively

### ISSUE THREAD

**Issue by Hoverbear** [humenda/Blg#1]
https://github.com/humenda/Blg/blob/3946f4e4cd71af5d7bacc5b191d22fed1e30bf8c/Ausarbeitung.tex#L69-L71

> Thesaurses are used in diverse use cases, ranging from general reformulation of 
 text passages by authors of texts, to information retrieval applications, to 
improve the recall for search queries.

This sentence has 'used in ... use cases'. Unless you are implying that Thesaurus are not used in some of their use cases, this is redundant. 

Also note spelling of 'Thesaurus'. Plural is 'Thesauruses' or 'Thesauri', either works but be consistent.

One option:

> Thesauruses have a diverse range of use cases, from general reformulation of 
 text passages by authors of texts, to information retrieval applications, to 
improve the recall for search queries.

Or, for example:

> Thesauruses are applied in a range of diverse use cases, from general reformulation of 
 text passages by authors of texts, to information retrieval applications, to 
improve the recall for search queries.

The final ', to improve' really catches the eye so close to the previous. It could be reworded.

(Since this is the first grab of the paper let's really make sure it's perfect! =D)

**Comment by humenda** [comment]
>> Thesauruses are applied in a range of diverse use cases, from general reformulation of 
[…]
Sounds good, thanks.

>The final ', to improve' really catches the eye so close to the previous. It could be reworded.
Excuse me, what do you mean?

**Comment by Hoverbear** [comment]
@humenda regarding ', to improve' it just reads a bit awkwardly. I wonder if we could work that into the previous sentence or something a bit nicer. This is a very minor nit though.

**Comment by humenda** [comment]
Closed as approved by the professional
