### ISSUE TITLE
". However, ..."

### ISSUE THREAD

**Issue by Hoverbear** [humenda/Blg#21]
In general the text ". However, ..." or ", however, ..." should be treated as a 'code smell'. They are not necessarily wrong, and are appropriate in some contexts, but try to use them sparingly and only where there isn't another good option.

More info: https://english.stackexchange.com/questions/79/is-it-acceptable-to-start-a-sentence-with-however

**Comment by humenda** [comment]
Thanks, I realised that I used this a bit too often. I have now reduced the number of sentences starting with however. If any of the remaining Howevers looks odd, please let me know.
