### ISSUE TITLE
Title formatting

### ISSUE THREAD

**Issue by huljar** [humenda/Blg#24]
Currently, only the last word ("Word2vec") of the title is on a new line. I'd suggest putting "using Word2vec" both on the second line, looks better.

**Comment by humenda** [comment]
Thanks

**Comment by huljar** [comment]
Now there is almost no space between the two lines. It should be slightly increased.

**Comment by humenda** [comment]
You have push rights now, would you please adjust the space, I'm struggeling to
reason properly about this :).
