### ISSUE TITLE
Chapter 2 first sentence: weird structure, maybe split sentence?

### ISSUE THREAD

**Issue by huljar** [humenda/Blg#32]
My suggestion: "... in a timely efficient manner. In addition, it yields surprisingly good word embeddings, capturing ..."

**Comment by humenda** [comment]
Hi

>My suggestion: "... in a timely efficient manner. In addition, it yields surprisingly good word embeddings, capturing ..."
Nah, it's not an addition. The trade-off  is usually either good results and
extremly expensive computation or shorter computation and less accurate
embeddings. Do you have a different suggestion?

**Comment by huljar** [comment]
The current wording also suggests that it provides both efficient learning and surprisingly good results at the same time. I thought this is what makes Word2vec gain so much attention.

In this case, you should mention that there is a trade-off, and that focusing on one aspect worsens the other. In any case, don't cram all that into one sentence :)
