### ISSUE TITLE
2.4.1 first sentence: usage of bibliography reference

### ISSUE THREAD

**Issue by huljar** [humenda/Blg#48]
"Already in 1993, [7] introduced a novel system ..." I would write the authors' names in addition to the number, i.e. "Already in 1993, Foo et al. [7] introduced a novel system ..." or "Already in 1993, Foo et al. introduced a novel system ... [7]"

**Comment by humenda** [comment]
Would you use both author and reference number? I usually use either
`\citeauthor` or `\cite`, rarely both.

**Comment by huljar** [comment]
Yes, I would use both.
