### ISSUE TITLE
2.4.1 paragraph 2: missing source

### ISSUE THREAD

**Issue by huljar** [humenda/Blg#50]
"... using a weighted Jaccard measure, which was introduced in an earlier paper." There is no reference to this "earlier paper", this should be added.

**Comment by humenda** [comment]
I'm not sure whether I need to recite their papers, neither have I read it nor
is it relevant. What about "introduced in an earlier work cited by
\cite{thispaper}"?

**Comment by huljar** [comment]
I don't know, if it is irrelevant, maybe leave the part with "earlier paper" out altogether?
